plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/jest"
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/prettier"
  - './toolkit/rollup'
hooks:
  git:precommit:
    - SecretSquirrel
  test:local:
    - Eslint
    - JestLocal
  test:ci:
    - Eslint
    - JestCI
options: {}
